# Generated by Django 3.1.6 on 2021-03-22 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('INR', 'Indian (Rupee)'), ('USD', 'United States (Dollar)'), ('EURO', 'European (euro)'), ('DIRAHAM', 'United Amirates (Dirham)'), ('YAN', 'Chinese (Yuan)'), ('PAKISTANI RUPEE', 'Pakistani (Rupee)')], default='-', max_length=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.IntegerField()),
                ('age', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(default='Male', max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_on', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='kyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancard', models.ImageField(upload_to='images')),
                ('aadhar', models.ImageField(upload_to='images')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_from', models.CharField(choices=[('USD', 'United States (Dollar)'), ('EURO', 'European (euro)'), ('DIRAHAM', 'United Amirates (Dirham)'), ('YAN', 'Chinese (Yuan)'), ('PAKISTANI RUPEE', 'Pakistani (Rupee)')], default='-', max_length=15)),
                ('currency_to', models.CharField(choices=[('INR', 'Indian (Rupee)')], default='-', max_length=3)),
                ('forex_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('inr_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('forex_rate', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('Commission_amount', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreateOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_from', models.CharField(choices=[('USD', 'United States (Dollar)'), ('EURO', 'European (euro)'), ('DIRAHAM', 'United Amirates (Dirham)'), ('YAN', 'Chinese (Yuan)'), ('PAKISTANI RUPEE', 'Pakistani (Rupee)')], default='-', max_length=15)),
                ('currency_to', models.CharField(choices=[('INR', 'Indian (Rupee)')], default='-', max_length=3)),
                ('forex_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('inr_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('forex_rate', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('Commission_amount', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
