# Generated by Django 3.1.6 on 2021-03-19 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('INR', 'Indian (Rupee)'), ('USD', 'United States (Dollar)'), ('EURO', 'European (euro)'), ('DIRAHAM', 'United Amirates (Dirham)'), ('YAN', 'Chinese (Yuan)'), ('PAKISTANI RUPEE', 'Pakistani (Rupee)')], default='-', max_length=15)),
                ('value', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='kyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancard', models.ImageField(upload_to='images')),
                ('aadhar', models.ImageField(upload_to='images')),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_from', models.CharField(choices=[('USD', 'United States (Dollar)'), ('EURO', 'European (euro)'), ('DIRAHAM', 'United Amirates (Dirham)'), ('YAN', 'Chinese (Yuan)'), ('PAKISTANI RUPEE', 'Pakistani (Rupee)')], default='-', max_length=15)),
                ('currency_to', models.CharField(choices=[('INR', 'Indian (Rupee)')], default='-', max_length=3)),
                ('forex_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('inr_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
