# Generated by Django 3.1.6 on 2021-03-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='aadhar',
            field=models.ImageField(upload_to='images/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='pancard',
            field=models.ImageField(upload_to='images/% Y/% m/% d/'),
        ),
    ]
