# Generated by Django 3.1.6 on 2021-03-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0003_auto_20210309_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='aadhar',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='pancard',
            field=models.ImageField(upload_to=''),
        ),
    ]
