# Generated by Django 3.1.6 on 2021-03-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exapp', '0004_auto_20210309_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='aadhar',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='pancard',
            field=models.ImageField(upload_to='images'),
        ),
    ]
